# Generated by Django 5.0.4 on 2024-04-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA_PUBLICACION', models.DateField()),
                ('PAIS_PRISION', models.CharField(max_length=100)),
                ('CONSULADO', models.CharField(max_length=100)),
                ('DELITO', models.CharField(max_length=100)),
                ('EXTRADITADO_Y_O_REPATRIADO', models.CharField(max_length=100)),
                ('SITUACION_JURIDICA', models.CharField(max_length=100)),
                ('GENERO', models.CharField(max_length=50)),
                ('GRUPO_EDAD', models.CharField(max_length=50)),
                ('UBICACION_PAIS', models.CharField(max_length=255)),
                ('CANTIDAD', models.IntegerField()),
                ('LATITUD', models.FloatField()),
                ('LONGITUD', models.FloatField()),
            ],
        ),
    ]
